apiVersion: v1
kind: Service
metadata:
  name: remarque
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.serviceIP | quote }}
spec:
  type: LoadBalancer
  selector:
    app: remarque
  ports:
    - name: http
      port: 8000
      targetPort: 8000
